name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - intesar
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Blocker
        - Non-Blocker
    validations:
      required: true     
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Write a brief report..."
    validations:
      required: true

  - type: markdown
    id: security-best-practices
    attributes:
      value: |
        ##### Security Best Practices:
        - Never share credentials, privacy information, and organization/project sensitive data.
      
  - type: markdown
    id: how-we-handle-bugs
    attributes:
      value: |
        ##### How we handle bugs: 
        - Duplicate, wont-fix, invalid tagged bugs are closed automatically.
        - Fixed and released bugs are closed automatically.
        - Fixed bugs go live as part of our weekend releases.
        - Blockers bugs go live as part of nightly releases.
        - To escalate an issue, please reach us at our support email handle.

