blank_issues_enabled: false
contact_links:
  - name: Apisec Release Notes
    url: https://apisec-inc.github.io/releases
    about: Check our newly released features and security fixes
  - name: Apisec Documentation
    url: https://www.apisec.ai/documentation/
    about: Learn how to onboard, best-practices, and continuously secure APIs
