name: Feature Request
description: File a feature request report
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - intesar
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Please describe your problem?
      description: Is your feature request related to a problem? Please describe.?
      placeholder: Explain us your problem!
      value: "Write a brief problem report..."
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: How important is this feature?
      description: How important is this feature?
      options:
        - Very Important
        - Nice to Have
    validations:
      required: true     
  - type: textarea
    id: how-to-solve
    attributes:
      label: Describe the solution you'd like?
      description: Describe the solution you'd like?
      placeholder: Explain us your solution!
      value: "Write a brief solution report..."
    validations:
      required: true      
  - type: markdown
    id: how-we-handle-features
    attributes:
      value: |
        ##### How we handle features: 
        - Duplicate, wont-fix, invalid tagged submissions are closed automatically.
        - Implemented and released features are closed automatically.
        - Implemented features go live as part of our weekend.
        - To escalate an issue, please reach us at our support email handle.
