name: Vulnerability Report
description: File a vulnerability report
title: "[Vulnerability]: "
labels: ["vulnerability"]
assignees:
  - intesar
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Critical
        - High
        - Medium
    validations:
      required: true     
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Write a brief report..."
    validations:
      required: true

  - type: markdown
    id: security-best-practices
    attributes:
      value: |
        ##### Security Best Practices:
        - Never share credentials, privacy information, and organization/project sensitive data.      
  - type: markdown
    id: how-we-handle-vulnerabilities
    attributes:
      value: |
        ##### How we handle vulnerabilities: 
        - Duplicate, wont-fix, invalid tagged vulnerabilities are closed automatically.
        - Fixed and released vulnerabilities are closed automatically.
        - Fixed vulnerabilities go live as part of our weekend and nightly releases.
        - To escalate an issue, please reach us at our support email handle.
